runtime: nodejs14

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1

default_expiration: "30d"

handlers:
  - url: /assets
    static_dir: dist/assets
  - url: /(.*\.(json|ico|js))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
    expiration: "0s"
